; write fd msg len
%macro write 3
	mov ebx, %1
	mov ecx, %2
	mov edx, %3
	mov eax, 4	; overwrite eax LAST, since it might also be arg 1,2,3
	int 0x80
%endmacro

; read 
; ecx is what we read
%macro read 3
	mov ebx, %1
	mov ecx, %2
	mov edx, %3
	mov eax, 3	; overwrite eax LAST, since it might also be arg 1,2,3
	int 0x80
%endmacro

; exit 1
%macro exit 1
	mov ebx, %1
	mov eax, 1	; overwrite eax LAST, since it might also be arg 1
	int 0x80
%endmacro
